name: Sync_Download

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
  schedule:
    - cron: "30 15 1 */3 *"

jobs:
  sync_download:
    if: ${{ github.actor == 'gendloop' || github.actor == 'XiGeoAlgorithm' }}
    runs-on: ubuntu-latest
    steps:
      - name: sync-download
        uses: gendloop/sync-download@main
        with:
          token: ${{ secrets.GENDLOOP_ACCESS_TOKEN }}
