name: Sync_Download

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
  schedule:
    - cron: '30 15 1 * *'

jobs:
  sync_download:
    runs-on: ubuntu-latest
    steps:
      - name: sync-download
        uses: gendloop/sync-download@v1.0.2
        with:
          token: ${{ secrets.GENDLOOP_ACCESS_TOKEN }}
